<a href="https://colab.research.google.com/github/DAGP1145/Mineriadedatos/blob/main/Analizando_el_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/7to semestre/Mineria de datos/Actividad/books.csv")

# Variables categoricas

In [4]:
df.columns

Index(['catalog_position', 'title', 'author', 'year_published', 'genre',
       'section', 'total_copies', 'times_borrowed', 'last_borrowed_date',
       'rating', 'ratings_count', 'price', 'language', 'page_count',
       'dimensions_width', 'dimensions_thickness', 'dimensions_height',
       'catalog_shelf', 'catalog_row', 'catalog_row_number'],
      dtype='object')

In [35]:
df.shape

(2090, 20)

In [31]:
df.head()

,catalog_position,title,author,year_published,genre,section,total_copies,times_borrowed,last_borrowed_date,rating,ratings_count,price,language,page_count,dimensions_width,dimensions_thickness,dimensions_height,catalog_shelf,catalog_row,catalog_row_number
0,A1-B1-0001,Enormous Room,E. E. Cummings,1949.0,Drama,Fiction,5.0,3.0,1/6/2025,4.14,2.0,14.66,en,249.0,4.98,0.60,7.97,A1,B1,1
1,A1-B1-0002,Plutarchi Vitae parallelae,Plutarch,1478.0,Biography & Autobiography,History,4.0,1.0,3/19/2024,NaN,NaN,9.99,en,241.0,5.74,1.12,8.08,A1,B1,2
2,A1-B1-0003,The water-babies,Charles Kingsley,1863.0,Fantasy,Children,6.0,6.0,6/5/2024,4.21,6.0,13.89,en,228.0,7.70,0.70,5.10,A1,B1,3
3,A1-B1-0004,Kipps,H. G. Wells,1900.0,Comedy,Fiction,4.0,5.0,11/6/2024,4.44,4.0,370.00,en,386.0,5.08,0.98,7.80,A1,B1,4
4,A1-B1-0005,Man and Superman,George Bernard Shaw,1903.0,Drama,Fiction,5.0,2.0,1/16/2025,4.46,2.0,10.99,en,220.0,5.08,1.22,7.80,A1,B1,5

In [30]:
df.dtypes

catalog_position         object
title                    object
author                   object
year_published          float64
genre                    object
section                  object
total_copies            float64
times_borrowed          float64
last_borrowed_date       object
rating                  float64
ratings_count           float64
price                   float64
language                 object
page_count              float64
dimensions_width        float64
dimensions_thickness    float64
dimensions_height       float64
catalog_shelf            object
catalog_row              object
catalog_row_number        int64
dtype: object

# select_dtypes
Este método crea un nuevo DataFrame que contiene únicamente las columnas de los tipos que especifiques.

In [10]:
df_objetos = df.select_dtypes(include=['object'])

In [12]:
# Para columnas de tipo 'object' (que usualmente son texto/categorías)
print(df_objetos.columns)

Index(['catalog_position', 'title', 'author', 'genre', 'section',
       'last_borrowed_date', 'language', 'catalog_shelf', 'catalog_row'],
      dtype='object')

In [16]:
df_objetos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2090 entries, 0 to 2089
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   catalog_position    2090 non-null   object
 1   title               2090 non-null   object
 2   author              2090 non-null   object
 3   genre               2039 non-null   object
 4   section             2032 non-null   object
 5   last_borrowed_date  2074 non-null   object
 6   language            2087 non-null   object
 7   catalog_shelf       2090 non-null   object
 8   catalog_row         2090 non-null   object
dtypes: object(9)
memory usage: 147.1+ KB

In [23]:
df_objetos.isnull().sum()

catalog_position       0
title                  0
author                 0
genre                 51
section               58
last_borrowed_date    16
language               3
catalog_shelf          0
catalog_row            0
dtype: int64

In [59]:
df_objetos['section'].isnull().value_counts()

section
False    2032
True       58
Name: count, dtype: int64

# Variables numericas

In [68]:
df['total_copies', 'times_borrowed', 'rating','ratings_count', 'price' ].describe().round()

,year_published,total_copies,times_borrowed,rating,ratings_count,price,page_count,dimensions_width,dimensions_thickness,dimensions_height,catalog_row_number
count,2086.0,2077.0,2084.0,1766.0,1762.0,1879.0,2085.0,2090.0,2089.0,2090.0,2090.0
mean,1871.0,5.0,45.0,4.0,48.0,318.0,357.0,6.0,1.0,8.0,41.0
std,116.0,2.0,172.0,0.0,250.0,4287.0,369.0,1.0,1.0,1.0,24.0
min,1200.0,1.0,0.0,1.0,1.0,0.0,2.0,4.0,0.0,4.0,1.0
25%,1833.0,5.0,2.0,4.0,2.0,5.0,188.0,5.0,1.0,8.0,20.0
50%,1900.0,5.0,4.0,5.0,4.0,10.0,294.0,6.0,1.0,8.0,40.0
75%,1932.0,6.0,9.0,5.0,10.0,15.0,432.0,6.0,1.0,9.0,61.0
max,2999.0,46.0,2256.0,5.0,6330.0,95000.0,7858.0,22.0,24.0,15.0,95.0

In [69]:
df['year_published'].isnull().value_counts()

year_published
False    2086
True        4
Name: count, dtype: int64