<a href="https://colab.research.google.com/github/DAGP1145/Mineriadedatos/blob/main/Mineria_De_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fuente: https://exoplanetarchive.ipac.caltech.edu/index.html

Disponemos de muchas fuentes de informaciòn de las cuales teniamos dos principales opciones:

Sistema planetarios o sistemas planetarios compuestos.

La diferencia es que uno esta compuesto de un estudio en especifico por lo tanto lo datos son consistentes. Pero la desventaja es que podrian faltar datos porque simplemente ese estudio no midiò todo.

Por otro lado la segunda tabla esta compuesta de distintas publicaciones y las junta para crear una sola fila por planeta, por lo tanto es mas completa. El problema es que esa información puede no ser consistente, porque viene de distintos estudios que usaron métodos diferentes.

Se seleccionó la tabla de Parámetros Compuestos, ya que proporciona una única fila por planeta con un conjunto de datos más completo, lo que facilita el análisis y la aplicación de técnicas de minería de datos, aun cuando los datos no sean completamente consistentes entre sí.
# Descripción de las variables seleccionadas
## Variables Cuantitativas discretas
sy_snum : Corersponde al numero de estrella.

sy_pnum: Corresponde al numero de planetas.

sy_mnum: Corresponde al numero de lunas.

disc_year: Año en que se descubrió el planeta.
## Variables Cuantitativas Continuas
pl_orbper: Período orbital del planeta medido en días terrestres.

pl_dens: Densidad media del planeta.
pl_rade / pl_radj (50 nulos c/u): Radio del planeta medido en radios terrestres y de Júpiter, respectivamente.

pl_orbeccen: Excentricidad orbital; indica qué tan elíptica u ovalada es la órbita del planeta.

pl_eqt: Temperatura de equilibrio del planeta (basada en el balance de energía con su estrella).

st_teff: Temperatura efectiva de la estrella (basada en su radiación electromagnética).

st_rad: Radio de la estrella, medido en unidades de radios solares.

st_mass: Masa de la estrella medida en masas solares.

st_met: Metalicidad de la estrella (proporción de metales frente al hidrógeno).

st_logg: Gravedad superficial de la estrella (aceleración gravitacional).

sy_dist: Distancia al sistema planetario medida en pársecs.
## Variables Cualitativas
### Variables Cualitativas Nominales
pl_name: Corresponde al nomnbre del planeta

hostname: corresponde a la estrella anfitriona.

discoverymethod: Corresponde al metodo de descubrimiento.

disc_facility: Corresponde al Lugar de observación del descubrimiento del planeta (Tierra o Espacio)

disc_telescope: Corresponde al telescopio. Nombre del telescopio utilizado para las observaciones del descubrimiento del planeta

disc_instrument: Corresponde al Nombre del instrumento de observación para el descubrimiento de planetas.
### Variables Cualitativas Ordinales
st_spectype: Clasificación espectral de la estrella (sistema Morgan-Keenan).

# Descripción de las variables seleccionadas

## Variables Cuantitativas Discretas

| Variable    | Descripción                                    |
|:------------|:-----------------------------------------------|
| `sy_snum`     | Número de estrellas en el sistema planetario   |
| `sy_pnum`     | Número de planetas en el sistema               |
| `sy_mnum`     | Número de lunas en el sistema                  |
| `disc_year`   | Año en que se descubrió el planeta             |

## Variables Cuantitativas Continuas

| Variable      | Descripción                                                                 |
|:--------------|:----------------------------------------------------------------------------|
| `pl_orbper`   | Período orbital del planeta medido en días terrestres                       |
| `pl_dens`     | Densidad media del planeta                                                  |
| `pl_rade`     | Radio del planeta medido en radios terrestres                               |
| `pl_radj`     | Radio del planeta medido en radios de Júpiter                               |
| `pl_orbeccen` | Excentricidad orbital (qué tan elíptica es la órbita)                     |
| `pl_eqt`      | Temperatura de equilibrio del planeta                                       |
| `st_teff`     | Temperatura efectiva de la estrella                                         |
| `st_rad`      | Radio de la estrella, medido en unidades de radios solares                  |
| `st_mass`     | Masa de la estrella, medida en masas solares                                |
| `st_met`      | Metalicidad de la estrella (proporción de metales)                          |
| `st_logg`     | Gravedad superficial de la estrella                                         |
| `sy_dist`     | Distancia al sistema planetario medida en pársecs                           |

## Variables Cualitativas

### Variables Cualitativas Nominales

| Variable          | Descripción                                                                       |
|:------------------|:----------------------------------------------------------------------------------|
| `pl_name`         | Nombre del planeta                                                                |
| `hostname`        | Nombre de la estrella anfitriona                                                  |
| `discoverymethod` | Método de descubrimiento del planeta                                              |
| `disc_facility`   | Lugar de observación del descubrimiento del planeta (Tierra o Espacio)           |
| `disc_telescope`  | Nombre del telescopio utilizado                                                   |
| `disc_instrument` | Nombre del instrumento de observación para el descubrimiento de planetas           |

### Variables Cualitativas Ordinales

| Variable      | Descripción                                                                     |
|:--------------|:--------------------------------------------------------------------------------|
| `st_spectype` | Clasificación espectral de la estrella (sistema Morgan-Keenan)                  |

# Importación de librerías

In [2]:
import pandas as pd # Estructura y manipulación de datos
import numpy as np #Programación vectorial

# Carga de los datos

In [3]:
url = 'https://raw.githubusercontent.com/DAGP1145/Mineriadedatos/refs/heads/main/PSCompPars_2026.04.21_08.17.48.csv'
df = pd.read_csv(url, sep=",", comment="#")

#Exploración inicial de los datos

In [4]:
display(df.head())

,pl_name,hostname,sy_snum,sy_pnum,sy_mnum,discoverymethod,disc_year,disc_locale,disc_facility,disc_telescope,...,st_loggerr1,st_loggerr2,st_logglim,st_dens,st_denserr1,st_denserr2,st_denslim,sy_dist,sy_disterr1,sy_disterr2
0,11 Com b,11 Com,2,1,0,Radial Velocity,2007.0,Ground,Xinglong Station,2.16 m Telescope,...,0.08,-0.08,0.0,NaN,NaN,NaN,NaN,93.1846,1.9238,-1.9238
1,11 UMi b,11 UMi,1,1,0,Radial Velocity,2009.0,Ground,Thueringer Landessternwarte Tautenburg,2.0 m Alfred Jensch Telescope,...,0.07,-0.07,0.0,NaN,NaN,NaN,NaN,125.3210,1.9765,-1.9765
2,14 And b,14 And,1,1,0,Radial Velocity,2008.0,Ground,Okayama Astrophysical Observatory,1.88 m Telescope,...,0.06,-0.07,0.0,NaN,NaN,NaN,NaN,75.4392,0.7140,-0.7140
3,14 Her b,14 Her,1,2,0,Radial Velocity,2002.0,Ground,W. M. Keck Observatory,10 m Keck I Telescope,...,0.02,-0.02,0.0,1.273928,0.349533,-0.30728,0.0,17.9323,0.0073,-0.0073
4,16 Cyg B b,16 Cyg B,3,1,0,Radial Velocity,1996.0,Ground,Multiple Observatories,Multiple Telescopes,...,0.01,-0.01,0.0,1.011029,0.292731,-0.20081,0.0,21.1397,0.0110,-0.0111

In [5]:
display(df.tail())

,pl_name,hostname,sy_snum,sy_pnum,sy_mnum,discoverymethod,disc_year,disc_locale,disc_facility,disc_telescope,...,st_loggerr1,st_loggerr2,st_logglim,st_dens,st_denserr1,st_denserr2,st_denslim,sy_dist,sy_disterr1,sy_disterr2
6155,ups And b,ups And,2,3,0,Radial Velocity,1996.0,Ground,Lick Observatory,3.0 m C. Donald Shane Telescope,...,0.024844,-0.024844,0.0,0.36993,0.099225,-0.071557,0.0,13.4054,0.06350,-0.06290
6156,ups And c,ups And,2,3,0,Radial Velocity,1999.0,Ground,Multiple Observatories,Multiple Telescopes,...,0.024844,-0.024844,0.0,0.36993,0.099225,-0.071557,0.0,13.4054,0.06350,-0.06290
6157,ups And d,ups And,2,3,0,Radial Velocity,1999.0,Ground,Multiple Observatories,Multiple Telescopes,...,0.024844,-0.024844,0.0,0.36993,0.099225,-0.071557,0.0,13.4054,0.06350,-0.06290
6158,ups Leo b,ups Leo,1,1,0,Radial Velocity,2021.0,Ground,Okayama Astrophysical Observatory,1.88 m Telescope,...,0.090000,-0.090000,0.0,NaN,NaN,NaN,NaN,52.5973,0.92720,-0.89630
6159,xi Aql b,xi Aql,1,1,0,Radial Velocity,2007.0,Ground,Okayama Astrophysical Observatory,1.88 m Telescope,...,0.080000,-0.080000,0.0,NaN,NaN,NaN,NaN,56.1858,0.55975,-0.55975

La pagina web importa los datos bajo estos criterios:

1.   Elige el valor por defecto entre las distintas publicaciones de un mismo valor si fue definido.

2.   Si no existe, elige el valor con menor incertidumbre entre las distintas trasacciones de un mismo dato.

> Se mide como un rango alrededor del valor (“± algo”) por ejemplo: 10 ± 2 significa que el valor real puede estar entre 8 y 12.

3.  Si hay empate en la incertidumbre, elige el valor de la publicación más reciente

La base de datos te entrega por defecto datos que ya fueron seleccionados automáticamente para ser el más útil, pero no necesariamente el más consistente entre sí. Pero para efectos practicos no sera necesario tomar esta condición como una desventaja. A continuación seleccionaremos las columnas que queremos utilizar, esto lo hacemos para tener una base de datos más simplificada
al Dataframe original.

Como primera observación. Notaremos que en nuestra base de datos existen columnas adicionales con nombres similares, pero con sufijos numéricos. Esto se debe a que representan la incertidumbre del valor principal. Pero para efectos practicos solo se va a utilizar el valor sin numero el numero de referencia.

Ejemplo:

st_dens: es el dato que representa la densidad del sol pero para ese mismo dato existen columnas como:

Ejemplo: st_denserr1 correspone al límite superior del margen de error y st_denserr2 corresponde al límite inferior del margen de error.

In [14]:
systemplanets = df[['pl_name', 'hostname', 'sy_snum', 'sy_pnum', 'sy_mnum', 'discoverymethod', 'disc_year', 'disc_facility', 'disc_telescope', 'disc_instrument', 'pl_orbper', 'pl_rade', 'pl_radj', 'pl_dens', 'pl_orbeccen', 'pl_eqt', 'st_spectype', 'st_teff', 'st_rad', 'st_mass', 'st_met', 'st_logg', 'sy_dist']]

# Análisis de los datos

## Enfoque del Problema: Agrupación de Exoplanetas

Dado que nuestro objetivo es explorar los datos y aprender acerca de astronomía, hemos pensado que nuestra investigación este orientada a la **Agrupación de Exoplanetas** como la problemática principal.

El objetivo de este enfoque es identificar patrones y estructuras naturales dentro del conjunto de datos de exoplanetas, agrupando aquellos que comparten características similares. Esto nos permitirá:

*   **Descubrir tipos de exoplanetas:** Identificar si existen categorías o clases intrínsecas de exoplanetas basadas en sus propiedades físicas (radio, densidad, temperatura, etc.) y orbitales (período orbital, excentricidad).
*   **Exploración sin supervisión:** Al no requerir una variable objetivo predefinida, el clustering es ideal para una fase exploratoria, donde buscamos entender la variabilidad y la organización inherente de los datos.
*   **Identificación de puntos de interés:** Los grupos identificados pueden señalar características o patrones que merezcan una investigación más profunda, sugiriendo preguntas para futuros análisis.

Este proceso nos ayudará a familiarizarnos con el dataset de una manera intuitiva y visual, sentando las bases para análisis más complejos en el futuro.

In [18]:
display(systemplanets.sample())

,pl_name,hostname,sy_snum,sy_pnum,sy_mnum,discoverymethod,disc_year,disc_facility,disc_telescope,disc_instrument,...,pl_dens,pl_orbeccen,pl_eqt,st_spectype,st_teff,st_rad,st_mass,st_met,st_logg,sy_dist
3361,Kepler-1906 b,Kepler-1906,1,1,0,Transit,2021.0,Kepler,0.95 m Kepler Telescope,Kepler CCD Array,...,2.09,0.0,901.0,NaN,5868.0,0.894,0.987,-0.12,4.53,1360.63

In [ ]:
# df.shape para conocer las dimensiones de la base de datos.
systemplanets.shape

(6160, 23)

# Tipos de datos de las columnas

In [ ]:
# Con info() Podremos visualizar las columnas, los tipos de datos y su cantidad.
# Podriamos usar df.columns para conocer las columnas. Tambien podriamos utilizar df.dtypes para conocer los tipos de datos de cada columna.
# Pero con info es mas que suficiente para conocer ambas datos, además nos permite contabilizar los tipos de datos función que no hace con dtypes.
systemplanets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6160 entries, 0 to 6159
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          6160 non-null   object
 1   hostname         6160 non-null   object
 2   sy_snum          6160 non-null   int64
 3   sy_pnum          6160 non-null   int64
 4   sy_mnum          6160 non-null   int64
 5   discoverymethod  6160 non-null   object
 6   disc_year        6159 non-null   float64
 7   disc_facility    6160 non-null   object
 8   disc_telescope   6160 non-null   object
 9   disc_instrument  6160 non-null   object
 10  pl_orbper        5821 non-null   float64
 11  pl_rade          6110 non-null   float64
 12  pl_radj          6110 non-null   float64
 13  pl_dens          6021 non-null   float64
 14  pl_orbeccen      5221 non-null   float64
 15  pl_eqt           4596 non-null   float64
 16  st_spectype      2314 non-null   object
 17  st_teff          5866 non-null   float64
 18  st_rad           5842 non-null   float64
 19  st_mass          6152 non-null   float64
 20  st_met           5606 non-null   float64
 21  st_logg          5838 non-null   float64
 22  sy_dist          6133 non-null   float64
dtypes: float64(13), int64(3), object(7)
memory usage: 1.1+ MB

In [ ]:
#Pero no visualizamos cuáles son las columnas en su conjunto que pertenecen a cierto tipo de dato. A continuación lo hacemos.
df_objetos = systemplanets.select_dtypes(include=['object'])
df_int_floats = systemplanets.select_dtypes(include=['int', 'float'])

In [ ]:
display(df_objetos.columns.to_list())
print("Numero de columnas: ", sum(df_objetos.columns.value_counts()), '\n')
display(df_int_floats.columns.to_list())
print("Numero de columnas: ", sum(df_int_floats.columns.value_counts()))
# En total 7 columnas categoricas y para las columnas que componen los datos numericos corresponden a un total de 16. Conformando un total de 23 de columnas dentro de nuestro dataset.

['pl_name',
 'hostname',
 'discoverymethod',
 'disc_facility',
 'disc_telescope',
 'disc_instrument',
 'st_spectype']

Numero de columnas:  7

['sy_snum',
 'sy_pnum',
 'sy_mnum',
 'disc_year',
 'pl_orbper',
 'pl_rade',
 'pl_radj',
 'pl_dens',
 'pl_orbeccen',
 'pl_eqt',
 'st_teff',
 'st_rad',
 'st_mass',
 'st_met',
 'st_logg',
 'sy_dist']

Numero de columnas:  16

In [ ]:
systemplanets['st_spectype'].value_counts()

st_spectype
G0 V              65
G5 V              62
K0                61
M0 V              56
G5                54
                  ..
F9/G0              1
K1 IIIb Fe-0.5     1
B9 IV              1
B2 IV              1
G4 II-III          1
Name: count, Length: 327, dtype: int64

In [ ]:
systemplanets['discoverymethod'].value_counts()

discoverymethod
Transit                          4523
Radial Velocity                  1180
Microlensing                      278
Imaging                            96
Transit Timing Variations          40
Eclipse Timing Variations          17
Orbital Brightness Modulation       9
Pulsar Timing                       8
Astrometry                          6
Pulsation Timing Variations         2
Disk Kinematics                     1
Name: count, dtype: int64

In [ ]:
systemplanets['disc_instrument'].value_counts()

disc_instrument
Kepler CCD Array                 3332
TESS CCD Array                    769
Multiple Instruments              394
HARPS Spectrograph                232
HIRES Spectrometer                183
                                 ...
ACAM Auxiliary Port Camera          1
VIRCAM CCD Array                    1
NIRCam                              1
PRISM CCD                           1
HERCULES echelle spectrograph       1
Name: count, Length: 101, dtype: int64

In [ ]:
systemplanets['disc_facility'].value_counts()

disc_facility
Kepler                                          2783
Transiting Exoplanet Survey Satellite (TESS)     769
K2                                               549
Multiple Observatories                           351
La Silla Observatory                             302
                                                ...
KOINet                                             1
Teide Observatory                                  1
Infrared Survey Facility                           1
Leoncito Astronomical Complex                      1
University of Canterbury Mt John Observatory       1
Name: count, Length: 73, dtype: int64

In [ ]:
systemplanets['disc_telescope'].value_counts()

disc_telescope
0.95 m Kepler Telescope              3332
0.1 m TESS Telescope                  769
Multiple Telescopes                   400
3.6 m ESO Telescope                   234
Canon 200mm f/1.8L                    231
                                     ...
Automated Planet Finder Telescope       1
Perkins 1.8 m Telescope                 1
4 m ESO Vista Telescope                 1
1.0 m McLellan telescope                1
2.7m Harlan J. Smith Telescope          1
Name: count, Length: 84, dtype: int64

In [ ]:
systemplanets['disc_year'].value_counts()

disc_year
2016.0    1496
2014.0     869
2021.0     564
2022.0     369
2023.0     324
2018.0     315
2024.0     259
2025.0     244
2020.0     234
2019.0     196
2015.0     155
2017.0     151
2012.0     139
2011.0     135
2013.0     128
2010.0      97
2009.0      91
2026.0      74
2008.0      63
2007.0      52
2005.0      36
2006.0      32
2002.0      29
2004.0      27
2003.0      22
2000.0      16
1999.0      13
2001.0      12
1998.0       6
1996.0       6
1992.0       2
1995.0       1
1994.0       1
1997.0       1
Name: count, dtype: int64

# Tratamiento de valores nulos
Al analizar la calidad de los datos, se identificó una cantidad considerable de valores nulos en varias columnas clave del conjunto de datos. A continuación, se detallan las variables afectadas y su significado técnico:

In [ ]:
for feature in systemplanets.columns:
  print('Total de valores nulos de', feature, '=', systemplanets[feature].isna().sum())

Total de valores nulos de pl_name = 0
Total de valores nulos de hostname = 0
Total de valores nulos de sy_snum = 0
Total de valores nulos de sy_pnum = 0
Total de valores nulos de sy_mnum = 0
Total de valores nulos de discoverymethod = 0
Total de valores nulos de disc_year = 1
Total de valores nulos de disc_facility = 0
Total de valores nulos de disc_telescope = 0
Total de valores nulos de disc_instrument = 0
Total de valores nulos de pl_orbper = 339
Total de valores nulos de pl_rade = 50
Total de valores nulos de pl_radj = 50
Total de valores nulos de pl_dens = 139
Total de valores nulos de pl_orbeccen = 939
Total de valores nulos de pl_eqt = 1564
Total de valores nulos de st_spectype = 3846
Total de valores nulos de st_teff = 294
Total de valores nulos de st_rad = 318
Total de valores nulos de st_mass = 8
Total de valores nulos de st_met = 554
Total de valores nulos de st_logg = 322
Total de valores nulos de sy_dist = 27